import { Product, TimelineNode } from '@/app/types';

export const PRODUCTS: Product[] = [
  {
    id: 'trufa-caramelo-sal',
    name: 'Trufa de Caramelo Flor de Sal',
    price: 18,
    category: 'Trufas',
    image: './images/products/trufa-caramelo-sal.jpg',
    description: 'Uma trufa de chocolate amargo 70% cacau com recheio cremoso de caramelo artesanal, finalizada com flocos de flor de sal do nordeste brasileiro. A combinação perfeita entre o doce e o salgado.',
    flavorMap: { sweetness: 7, bitterness: 4, acidity: 2, creaminess: 9 },
    tastingNotes: 'Notas iniciais de caramelo toffee seguidas por um toque salino que realça o chocolate amargo. Final longo e sedoso.',
    ingredients: ['Chocolate amargo 70% cacau', 'Açúcar mascavo', 'Creme de leite fresco', 'Flor de sal', 'Manteiga sem sal', 'Glucose'],
    allergens: ['Leite', 'Soja'],
    pairings: [
      { name: 'Espumante Brut', type: 'Vinho' },
      { name: 'Café espresso', type: 'Café' },
      { name: 'Whisky single malt', type: 'Destilado' },
    ],
    reviews: [
      { author: 'Mariana S.', rating: 5, date: '2025-03-15', text: 'A melhor trufa que já comi. O caramelo é perfeito, não é enjoativo.' },
      { author: 'Carlos R.', rating: 5, date: '2025-02-28', text: 'Presenteei minha mãe e ela ficou encantada. A embalagem é linda!' },
      { author: 'Ana P.', rating: 4, date: '2025-01-10', text: 'Muito boa, mas achei o sal um pouco forte para o meu paladar.' },
    ],
    isEasterEggTarget: true,
  },
  {
    id: 'bombom-framboesa',
    name: 'Bombom de Framboesa e Champagne',
    price: 22,
    category: 'Bombons',
    image: './images/products/bombom-framboesa.jpg',
    description: 'Bombom de chocolate branco com ganache de framboesa fresca e um toque de champagne rosé. Cobertura brilhante com um sabor sofisticado.',
    flavorMap: { sweetness: 8, bitterness: 1, acidity: 6, creaminess: 8 },
    tastingNotes: 'Entrada frutada e ácida da framboesa, equilibrada pela doçura do chocolate branco. Final fresco com notas de champagne.',
    ingredients: ['Chocolate branco', 'Framboesa fresca', 'Creme de leite', 'Champagne rosé', 'Açúcar', 'Manteiga de cacau'],
    allergens: ['Leite', 'Soja'],
    pairings: [
      { name: 'Champagne rosé', type: 'Vinho' },
      { name: 'Chá de hibisco', type: 'Chá' },
    ],
    reviews: [
      { author: 'Juliana M.', rating: 5, date: '2025-04-02', text: 'Delicado e sofisticado. Perfeito para ocasiões especiais.' },
      { author: 'Ricardo L.', rating: 4, date: '2025-03-20', text: 'Muito bom, mas prefiro os sabores mais intensos de chocolate.' },
    ],
  },
  {
    id: 'praline-avela',
    name: 'Praliné de Avelã Torrada',
    price: 20,
    category: 'Bombons',
    image: './images/products/praline-avela.jpg',
    description: 'Clássico praliné de avelã torrada em pedaços crocantes, envolto em chocolate ao leite belga. Textura crocante e sabor intenso de avelã.',
    flavorMap: { sweetness: 6, bitterness: 3, acidity: 1, creaminess: 7 },
    tastingNotes: 'Avelã torrada em notas principais com um crocante irresistível. Chocolate ao leite suave equilibra a intensidade da castanha.',
    ingredients: ['Chocolate ao leite', 'Avelã torrada', 'Açúcar', 'Manteiga de cacau', 'Lecitina de soja'],
    allergens: ['Leite', 'Soja', 'Castanhas'],
    pairings: [
      { name: 'Café com leite', type: 'Café' },
      { name: 'Porto tawny', type: 'Vinho' },
    ],
    reviews: [
      { author: 'Fernando K.', rating: 5, date: '2025-03-25', text: 'O crocante da avelã é surreal. Compro sempre!' },
    ],
  },
  {
    id: 'trufa-vinho',
    name: 'Trufa de Vinho Quente e Especiarias',
    price: 24,
    category: 'Trufas',
    image: './images/products/trufa-vinho.jpg',
    description: 'Edição limitada de inverno. Trufa de chocolate amargo com ganache de vinho quente reduzido, canela, cravo e noz-moscada.',
    flavorMap: { sweetness: 5, bitterness: 6, acidity: 3, creaminess: 8 },
    tastingNotes: 'Aromas quentes de especiarias com fundo de vinho tinto encorpado. Final com notas de cravo e canela que aquecem o paladar.',
    ingredients: ['Chocolate amargo 70%', 'Vinho tinto seco', 'Canela', 'Cravo', 'Noz-moscada', 'Creme de leite', 'Açúcar'],
    allergens: ['Leite'],
    pairings: [
      { name: 'Vinho tinto Syrah', type: 'Vinho' },
      { name: 'Café coado forte', type: 'Café' },
    ],
    reviews: [
      { author: 'Paula G.', rating: 5, date: '2025-06-10', text: 'Perfeita para o inverno. As especiarias são muito bem equilibradas.' },
    ],
    badges: ['Edição Limitada'],
  },
  {
    id: 'bombom-cereja',
    name: 'Bombom de Cereja Confitada',
    price: 22,
    category: 'Bombons',
    image: './images/products/bombom-cereja.jpg',
    description: 'Bombom com recheio de cereja confitada em calda de kirsch, envolto em chocolate meio amargo. Uma explosão de sabor frutado.',
    flavorMap: { sweetness: 7, bitterness: 4, acidity: 5, creaminess: 6 },
    tastingNotes: 'Cereja doce e levemente ácida com um toque alcoólico do kirsch. Chocolate meio amargo cria um equilíbrio elegante.',
    ingredients: ['Chocolate meio amargo', 'Cereja confitada', 'Kirsch', 'Açúcar', 'Glucose'],
    allergens: ['Leite', 'Soja'],
    pairings: [
      { name: 'Gin tônica', type: 'Destilado' },
      { name: 'Chá de frutas vermelhas', type: 'Chá' },
    ],
    reviews: [
      { author: 'Lucia H.', rating: 4, date: '2025-05-01', text: 'Muito bom, mas esperava mais sabor de cereja no recheio.' },
    ],
  },
  {
    id: 'barra-nozes-mel',
    name: 'Barra de Chocolate com Nozes e Mel',
    price: 48,
    category: 'Barras',
    image: './images/products/barra-nozes-mel.jpg',
    description: 'Barra de chocolate amargo 55% com pedaços crocantes de nozes caramelizadas e mel silvestre. Uma combinação rústica e sofisticada.',
    flavorMap: { sweetness: 6, bitterness: 5, acidity: 2, creaminess: 5 },
    tastingNotes: 'Crocante inicial das nozes seguido pelo sabor terroso do chocolate. O mel traz uma doçura natural e floral.',
    ingredients: ['Chocolate amargo 55%', 'Nozes caramelizadas', 'Mel silvestre', 'Açúcar', 'Manteiga de cacau'],
    allergens: ['Leite', 'Soja', 'Castanhas'],
    pairings: [
      { name: 'Café preto forte', type: 'Café' },
      { name: 'Vinho do Porto', type: 'Vinho' },
    ],
    reviews: [
      { author: 'Roberto D.', rating: 5, date: '2025-04-18', text: 'A crocância das nozes é perfeita. Melhor barra artesanal que já provei.' },
    ],
  },
  {
    id: 'caixa-inverno',
    name: 'Coleção Caixa de Inverno — 12 unidades',
    price: 120,
    category: 'Coleções',
    image: './images/products/caixa-inverno.jpg',
    description: 'Caixa exclusiva de inverno com 12 unidades sortidas: trufas de vinho quente, bombons de cereja, pralinés de avelã e mais. Laço dourado artesanal.',
    flavorMap: { sweetness: 6, bitterness: 4, acidity: 3, creaminess: 7 },
    tastingNotes: 'Uma viagem pelos sabores mais acolhedores do inverno. Cada peça conta uma história de conforto e indulgência.',
    ingredients: ['Variedade de chocolates', 'Frutas confitadas', 'Especiarias', 'Castanhas', 'Cremes'],
    allergens: ['Leite', 'Soja', 'Castanhas', 'Ovos'],
    pairings: [
      { name: 'Vinho tinto encorpado', type: 'Vinho' },
      { name: 'Café expresso', type: 'Café' },
    ],
    reviews: [
      { author: 'Camila T.', rating: 5, date: '2025-06-05', text: 'Presenteei meu namorado e ele amou. A caixa é linda demais!' },
    ],
    badges: ['Mais Vendido'],
  },
  {
    id: 'trufa-classica',
    name: 'Trufa Clássica de Chocolate Amargo',
    price: 16,
    category: 'Trufas',
    image: './images/products/trufa-classica.jpg',
    description: 'A trufa clássica da Chocolaterie Château. Ganache de chocolate amargo 70% cacau, enrolada à mão e polvilhada com cacau em pó.',
    flavorMap: { sweetness: 4, bitterness: 7, acidity: 3, creaminess: 9 },
    tastingNotes: 'Intensidade pura do cacau de origem. Textura sedosa que derrete na boca. Final limpo e amargo elegante.',
    ingredients: ['Chocolate amargo 70% cacau', 'Creme de leite', 'Manteiga de cacau', 'Cacau em pó'],
    allergens: ['Leite', 'Soja'],
    pairings: [
      { name: 'Café espresso italiano', type: 'Café' },
      { name: 'Vinho do Porto vintage', type: 'Vinho' },
    ],
    reviews: [
      { author: 'Eduardo N.', rating: 5, date: '2025-03-01', text: 'A trufa clássica perfeita. Nada supera a simplicidade bem executada.' },
      { author: 'Bruna C.', rating: 4, date: '2025-02-14', text: 'Muito boa, mas prefiro as trufas com recheio.' },
    ],
  },
  {
    id: 'bombom-maracuja',
    name: 'Bombom de Maracujá',
    price: 18,
    category: 'Bombons',
    image: './images/products/bombom-maracuja.jpg',
    description: 'Bombom de chocolate branco com ganache de maracujá fresco e creme de leite. Uma explosão tropical em cada mordida.',
    flavorMap: { sweetness: 7, bitterness: 1, acidity: 8, creaminess: 7 },
    tastingNotes: 'Acidez vibrante do maracujá equilibra a doçura do chocolate branco. Final refrescante e levemente cítrico.',
    ingredients: ['Chocolate branco', 'Polpa de maracujá', 'Creme de leite', 'Açúcar', 'Manteiga de cacau'],
    allergens: ['Leite', 'Soja'],
    pairings: [
      { name: 'Prosecco', type: 'Vinho' },
      { name: 'Caipirinha', type: 'Coquetel' },
    ],
    reviews: [
      { author: 'Tatiana V.', rating: 5, date: '2025-04-25', text: 'O maracujá é super fresco! Perfeito para o verão.' },
    ],
  },
  {
    id: 'barra-70',
    name: 'Barra 70% Cacau — Origem Equador',
    price: 42,
    category: 'Barras',
    image: './images/products/barra-70.jpg',
    description: 'Barra de chocolate amargo 70% cacau de origem única do Equador. Notas de frutas secas, caramelo e um leve toque de café.',
    flavorMap: { sweetness: 3, bitterness: 8, acidity: 5, creaminess: 4 },
    tastingNotes: 'Notas de cereja seca e caramelo no início. Amargor médio com final longo de café torrado e cacau puro.',
    ingredients: ['Massa de cacau', 'Açúcar de cana', 'Manteiga de cacau', 'Lecitina de soja'],
    allergens: ['Soja'],
    pairings: [
      { name: 'Café especial', type: 'Café' },
      { name: 'Vinho tinto Malbec', type: 'Vinho' },
    ],
    reviews: [
      { author: 'Diego A.', rating: 5, date: '2025-03-30', text: 'Chocolate de origem excelente. Vale cada centavo.' },
    ],
  },
  {
    id: 'conjunto-trufas',
    name: 'Conjunto de Trufas — 6 unidades',
    price: 72,
    category: 'Coleções',
    image: './images/products/conjunto-trufas.jpg',
    description: 'Caixa com 6 trufas sortidas: caramelo flor de sal, clássica amarga, doce de leite, vinho quente, pistache e maracujá.',
    flavorMap: { sweetness: 6, bitterness: 4, acidity: 4, creaminess: 8 },
    tastingNotes: 'Uma degustação completa dos nossos sabores mais populares. Cada trufa uma experiência diferente.',
    ingredients: ['Variedade de chocolates', 'Cremes', 'Frutas', 'Especiarias'],
    allergens: ['Leite', 'Soja', 'Castanhas', 'Ovos'],
    pairings: [
      { name: 'Espumante', type: 'Vinho' },
      { name: 'Café', type: 'Café' },
    ],
    reviews: [
      { author: 'Vanessa R.', rating: 5, date: '2025-05-20', text: 'Ótimo para degustação! Adorei poder provar vários sabores.' },
    ],
  },
  {
    id: 'trufa-doce-leite',
    name: 'Trufa de Doce de Leite',
    price: 18,
    category: 'Trufas',
    image: './images/products/trufa-caramelo-sal.jpg',
    description: 'Trufa de chocolate ao leite com recheio generoso de doce de leite artesanal argentino. Cobertura com padrão de swirl.',
    flavorMap: { sweetness: 9, bitterness: 2, acidity: 1, creaminess: 10 },
    tastingNotes: 'Doçura intensa do doce de leite com textura cremosa e avelludada. Chocolate ao leite suave equilibra a riqueza.',
    ingredients: ['Chocolate ao leite', 'Doce de leite', 'Creme de leite', 'Manteiga de cacau'],
    allergens: ['Leite', 'Soja'],
    pairings: [
      { name: 'Café com leite', type: 'Café' },
      { name: 'Chá de canela', type: 'Chá' },
    ],
    reviews: [
      { author: 'Marcos S.', rating: 5, date: '2025-04-12', text: 'Sou viciado em doce de leite e essa trufa é simplesmente perfeita.' },
    ],
  },
  {
    id: 'bombom-pistache',
    name: 'Bombom de Pistache',
    price: 22,
    category: 'Bombons',
    image: './images/products/bombom-framboesa.jpg',
    description: 'Bombom de chocolate branco com ganache de pistache siciliano. Pedaços de pistache crocantes na cobertura.',
    flavorMap: { sweetness: 6, bitterness: 2, acidity: 2, creaminess: 8 },
    tastingNotes: 'Sabor característico do pistache com um leve toque salgado. Textura cremosa com crocante dos pedaços de pistache.',
    ingredients: ['Chocolate branco', 'Pasta de pistache', 'Pistache torrado', 'Creme de leite', 'Manteiga de cacau'],
    allergens: ['Leite', 'Soja', 'Castanhas'],
    pairings: [
      { name: 'Café árabe', type: 'Café' },
      { name: 'Chá verde', type: 'Chá' },
    ],
    reviews: [
      { author: 'Isabela M.', rating: 4, date: '2025-03-18', text: 'Muito bom! O pistache é intenso e de qualidade.' },
    ],
  },
  {
    id: 'barra-leite-caramelo',
    name: 'Barra Ao Leite com Caramelo',
    price: 38,
    category: 'Barras',
    image: './images/products/barra-nozes-mel.jpg',
    description: 'Barra de chocolate ao leite belga com veios de caramelo salgado artesanal. Uma combinação clássica e irresistível.',
    flavorMap: { sweetness: 8, bitterness: 2, acidity: 2, creaminess: 7 },
    tastingNotes: 'Caramelo salgado em camadas suaves no chocolate ao leite cremoso. Doçura confortável com um toque de flor de sal.',
    ingredients: ['Chocolate ao leite', 'Caramelo salgado', 'Flor de sal', 'Manteiga de cacau'],
    allergens: ['Leite', 'Soja'],
    pairings: [
      { name: 'Café latte', type: 'Café' },
      { name: 'Leite quente', type: 'Bebida' },
    ],
    reviews: [
      { author: 'Patricia L.', rating: 5, date: '2025-05-15', text: 'A combinação de caramelo salgado com chocolate ao leite é divina.' },
    ],
  },
  {
    id: 'caixa-presente-24',
    name: 'Caixa Presente — 24 unidades',
    price: 240,
    category: 'Presentes',
    image: './images/products/caixa-inverno.jpg',
    description: 'Nossa caixa de presente premium com 24 unidades sortidas. Laço dourado artesanal, cartão personalizado e embalagem de luxo.',
    flavorMap: { sweetness: 6, bitterness: 4, acidity: 3, creaminess: 7 },
    tastingNotes: 'A coleção completa da Chocolaterie Château em uma caixa de presente deslumbrante. Cada peça é uma obra de arte.',
    ingredients: ['Variedade completa de chocolates', 'Cremes', 'Frutas', 'Castanhas', 'Especiarias'],
    allergens: ['Leite', 'Soja', 'Castanhas', 'Ovos', 'Trigo'],
    pairings: [
      { name: 'Champagne', type: 'Vinho' },
      { name: 'Café especial', type: 'Café' },
    ],
    reviews: [
      { author: 'Gabriela F.', rating: 5, date: '2025-06-01', text: 'A caixa mais linda que já vi! Presenteei minha sogra e ela ficou sem palavras.' },
    ],
    badges: ['Caixa de Presente'],
  },
];

export const FEATURED_IDS = ['trufa-caramelo-sal', 'bombom-framboesa', 'praline-avela'];
export const SEASONAL_IDS = ['trufa-vinho', 'bombom-cereja', 'barra-nozes-mel', 'caixa-inverno'];

export const TIMELINE_NODES: TimelineNode[] = [
  {
    title: 'Seleção',
    description: 'Grãos de cacau Forastero cuidadosamente selecionados à mão em fazendas sustentáveis da Bahia',
  },
  {
    title: 'Torrefação',
    description: 'Torra lenta em tambores de aço inox, ajustada grão por grão para extrair notas de frutas secas',
  },
  {
    title: 'Moinho',
    description: 'Moagem em moinhos de pedra de granito por 72 horas para textura micronizada',
  },
  {
    title: 'Temperagem',
    description: 'Temperagem artesanal em mármore de Carrara para brilho e estalo perfeitos',
  },
  {
    title: 'Acabamento',
    description: 'Decoração manual com pó de ouro comestível, flor de sal e frutas cristalizadas',
  },
];

export const FREE_SHIPPING_THRESHOLD = 150;
export const SHIPPING_COST = 15;
